/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATree: typeof import('ant-design-vue/es')['Tree']
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect']
    Button: typeof import('./components/Button/Button.vue')['default']
    Card: typeof import('./components/Card/Card.vue')['default']
    CardList: typeof import('./components/Card/CardList.vue')['default']
    Icon: typeof import('./components/Icon/Icon.vue')['default']
    Loading: typeof import('./components/Loading/Loading.vue')['default']
    Menu: typeof import('./components/Menu/Menu.vue')['default']
    MyTree: typeof import('./components/MyTree/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Select/Select.vue')['default']
    SideMenu: typeof import('./components/Menu/SideMenu.vue')['default']
    Tooltip: typeof import('./components/Tooltip/Tooltip.vue')['default']
    ToolTip: typeof import('./components/ToolTip/ToolTip.vue')['default']
    Tree: typeof import('./components/Tree/Tree.vue')['default']
  }
}
